#!/usr/bin/env python3
"""Purge Bunny CDN for notes modified since last purge.

Tracks last purge timestamp in .last_purge_time. Only purges notes
whose frontmatter `lastmod` is newer than that timestamp.
Handles rate limiting with automatic retry.

Uses stdlib urllib instead of requests to avoid extra dependencies.
Derives purge paths from Hugo's public/ output instead of hand-rolled slug logic.
"""

import json
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

ROOT_DIR = Path(__file__).resolve().parent.parent
CONTENT_DIR = ROOT_DIR / "content"
PUBLIC_DIR = ROOT_DIR / "public"
TIMESTAMP_FILE = ROOT_DIR / ".last_purge_time"
BASE_URL = "https://www.ssp.sh/brain"
PURGE_API = "https://api.bunny.net/purge"
LASTMOD_RE = re.compile(r"^lastmod:\s*(.+)$", re.MULTILINE)


def get_last_purge_time() -> datetime:
    if TIMESTAMP_FILE.exists():
        ts = TIMESTAMP_FILE.read_text().strip()
        if ts:
            try:
                return datetime.fromisoformat(ts)
            except ValueError:
                print(f"WARNING: corrupt .last_purge_time ({ts!r}), falling back to today")
    return datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)


def save_purge_time(dt: datetime):
    TIMESTAMP_FILE.write_text(dt.isoformat())


def parse_lastmod(text: str) -> datetime | None:
    m = LASTMOD_RE.search(text)
    if not m:
        return None
    raw = m.group(1).strip()
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(raw, fmt)
        except ValueError:
            continue
    return None


def slug_from_public(md_path: Path) -> str | None:
    """Find the actual slug Hugo generated by matching content file to public/ dir.

    Hugo outputs content/foo.md as public/foo/index.html. We find it by
    scanning public/ for an index.html whose directory name matches.
    """
    stem = md_path.stem.lower()
    for d in PUBLIC_DIR.iterdir():
        if d.is_dir() and (d / "index.html").exists():
            if d.name == stem.replace(" ", "-"):
                return d.name
    # Fallback: scan all public dirs for the one whose index.html contains
    # a matching title or just return the dir that best matches the stem
    # Hugo urlize: lowercase, replace spaces with -, strip special chars, collapse dashes
    name = stem.replace(" ", "-")
    name = re.sub(r"[^a-z0-9-]", "", name)
    name = re.sub(r"-+", "-", name).strip("-")
    for d in PUBLIC_DIR.iterdir():
        if d.is_dir() and (d / "index.html").exists() and d.name == name:
            return d.name
    return None


def purge_url(slug: str, api_key: str) -> bool:
    """Purge a slug (with and without trailing slash). Returns True only on success."""
    headers = {"AccessKey": api_key}
    for suffix in [slug, f"{slug}/"]:
        url = f"{BASE_URL}/{suffix}" if suffix else f"{BASE_URL}/"
        params = urlencode({"url": url, "async": "true"})
        full_url = f"{PURGE_API}?{params}"
        while True:
            req = Request(full_url, method="POST", headers=headers, data=b"")
            try:
                with urlopen(req) as resp:
                    body = resp.read().decode()
                    try:
                        data = json.loads(body)
                        if data.get("reason") == "rate_limited":
                            wait = data.get("retry_after_seconds", 2)
                            print(f"  Rate limited, waiting {wait}s...")
                            time.sleep(wait + 0.5)
                            continue
                    except (ValueError, KeyError):
                        pass
                    break
            except HTTPError as e:
                if e.code == 429:
                    wait = int(e.headers.get("Retry-After", 2))
                    print(f"  Rate limited (429), waiting {wait}s...")
                    time.sleep(wait + 0.5)
                    continue
                print(f"  ERROR: {e.code} for {url}")
                return False
            except URLError as e:
                print(f"  ERROR: {e.reason} for {url}")
                return False
    return True


def main():
    api_key = os.environ.get("BUNNY_API_KEY")
    if not api_key:
        print("BUNNY_API_KEY not set")
        sys.exit(1)

    last_purge = get_last_purge_time()
    purge_start = datetime.now()
    print(f"Last purge: {last_purge.isoformat()}")

    changed = []
    for md_file in sorted(CONTENT_DIR.glob("*.md")):
        text = md_file.read_text(errors="replace")
        lastmod = parse_lastmod(text)
        if lastmod and lastmod > last_purge:
            changed.append(md_file)

    if not changed:
        print("No notes changed since last purge.")
        save_purge_time(purge_start)
        return

    print(f"Found {len(changed)} note(s) to purge:")
    failed = False
    for f in changed:
        slug = slug_from_public(f)
        if slug is None:
            print(f"  WARNING: no public dir found for {f.name}, skipping")
            continue
        if not purge_url(slug, api_key):
            failed = True
            print(f"  FAILED: ssp.sh/brain/{slug}")
        else:
            print(f"  Purged: ssp.sh/brain/{slug}")

    # Always purge the index page
    if not purge_url("", api_key):
        failed = True
        print("FAILED to purge brain index")
    else:
        print("Purged brain index")

    if failed:
        print("Some purges failed — NOT updating .last_purge_time")
        sys.exit(1)

    save_purge_time(purge_start)
    print(f"Done. Updated .last_purge_time to {purge_start.isoformat()}")


if __name__ == "__main__":
    main()
